l_russian:
  SETTINGS_PAGE_GRAPHICS: "Графіка"
  SETTINGS_PAGE_GAME: "Гра"
  SETTINGS_PAGE_SYSTEM: "Система"
  SETTINGS_PAGE_CONTROLS: "Керування"
  SETTINGS_PAGE_EDITOR: "Редактор"
  SETTINGS_PAGE_INTERFACE: "Інтерфейс"
  SETTINGS_PAGE_AUDIO: "Звук"
  SETTINGS_CATEGORY_SCREEN: "Екран"
  SETTINGS_CATEGORY_QUALITY: "Якість"
  OPTION_EASY: "Легко"
  OPTION_NORMAL: "Нормально"
  OPTION_HARD: "Складно"
  OPTION_NEVER: "Ніколи"
  OPTION_MONTHLY: "Щомісяця"
  OPTION_HALFYEAR: "Щопівроку"
  OPTION_YEARLY: "Щороку"
  OPTION_FIVE_YEAR: "Щоп'ять років"
  OPTION_NO_AUTOSAVE: "Не виконувати автозбереження"
  SETTINGS_CATEGORY_ACCOUNT: "Обліковий запис"
  SETTINGS_CATEGORY_SYSTEM: "Система"
  SETTINGS_CATEGORY_CONTROLS: "Керування"
  SETTINGS_CATEGORY_CAMERA: "Камера"
  SETTINGS_CATEGORY_AUDIO: "Звук"
  SETTINGS_CATEGORY_GUI: "Інтерфейс"
  SETTINGS_CATEGORY_INPUT_BINDINGS: "Прив'язка клавіш введення"
  DISCARD: "Скасувати"
  APPLY: "Застосувати"
  SAVE_AND_CLOSE: "ОК"
  SETTINGS: "Налаштування"
  REQUIRES_RESTART: "Потрібен перезапуск"
  REQUIRE_RESTART_DESCRIPTION: "Деякі зміни набудуть чинності лише після перезапуску."
  SETTINGS_INPUT_REMAP_INPUT: "Перевизначити введення"
  SETTINGS_INPUT_CONFIRM: "Підтвердити"
  SETTINGS_INPUT_CANCEL: "Скасувати"
  SETTINGS_INPUT_CLEAR: "Видалити"
  SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Зберегти профіль"
  SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Завантажити профіль"
  SETTINGS_INPUT_RESET_INPUT_PROFILE: "За замовчуванням"
  SETTINGS_INPUT_BINDING_TEXT: "Будь ласка, прив'яжіть клавішу до дії «$INPUT_ACTION$»:\n\n$INPUT_NAME$"
  SETTINGS_INPUT_BINDING_WARNING_TEXT: "Увага: Ця клавіша вже прив'язана до дії «$INPUT_ACTION$»!\nНатиснувши «$SETTINGS_INPUT_CONFIRM$», ви видалите попередню прив'язку"
  SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Увага: прив'язка не може складатися лише з клавіш-модифікаторів"
  SETTINGS_PAGE_ACCOUNT: "Обліковий запис"
  SETTING_TELEMETRY_CONSENT: "Надіслати додаткові телеметричні дані"
  SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T Згода на телеметрію\n#!Дозволити надсилання додаткових телеметричних даних до Paradox Interactive."