l_english:
  SETTINGS_PAGE_GRAPHICS: "Графіка"
  SETTINGS_PAGE_GAME: "Гра"
  SETTINGS_PAGE_SYSTEM: "Система"
  SETTINGS_PAGE_CONTROLS: "Керування"
  SETTINGS_PAGE_EDITOR: "Редактор"
  SETTINGS_PAGE_INTERFACE: "Інтерфейс"
  SETTINGS_PAGE_AUDIO: "Аудіо"
  SETTINGS_CATEGORY_SCREEN: "Екран"
  SETTINGS_CATEGORY_QUALITY: "Якість"
  OPTION_EASY: "Легко"
  OPTION_NORMAL: "Нормально"
  OPTION_HARD: "Важко"
  OPTION_NEVER: "Ніколи"
  OPTION_MONTHLY: "Щомісяця"
  OPTION_HALFYEAR: "Щопівроку"
  OPTION_YEARLY: "Щорічно"
  OPTION_FIVE_YEAR: "Щоп'ять років"
  OPTION_NO_AUTOSAVE: "Не зберігати автоматично"
  SETTINGS_CATEGORY_ACCOUNT: "Обліковий запис"
  SETTINGS_CATEGORY_SYSTEM: "Система"
  SETTINGS_CATEGORY_CONTROLS: "Керування"
  SETTINGS_CATEGORY_CAMERA: "Камера"
  SETTINGS_CATEGORY_AUDIO: "Аудіо"
  SETTINGS_CATEGORY_GUI: "ГІК"
  SETTINGS_CATEGORY_INPUT_BINDINGS: "Призначення клавіш"
  DISCARD: "Відкинути"
  APPLY: "Застосувати"
  SAVE_AND_CLOSE: "Гаразд"
  SETTINGS: "Налаштування"
  REQUIRES_RESTART: "Потрібен перезапуск"
  REQUIRE_RESTART_DESCRIPTION: "Деякі налаштування не набудуть чинності, доки ви не перезапустите гру."
  DISABLED_BECAUSE_IS_SET: "Вимкнено, оскільки '$SETTING_NAME$' встановлено на '$SETTING_VALUE$'"
  SETTINGS_INPUT_REMAP_INPUT: "Перепризначити ввід"
  SETTINGS_INPUT_CONFIRM: "Підтвердити"
  SETTINGS_INPUT_CANCEL: "Скасувати"
  SETTINGS_INPUT_CLEAR: "Очистити"
  SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Зберегти профіль"
  SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Завантажити профіль"
  SETTINGS_INPUT_RESET_INPUT_PROFILE: "Скинути до стандартних"
  SETTINGS_INPUT_BINDING_TEXT: "Будь ласка, оберіть прив'язку вводу для дії '$INPUT_ACTION$':\n\n$INPUT_NAME$"
  SETTINGS_INPUT_BINDING_WARNING_TEXT: "Попередження: Ця прив'язка вводу вже існує для '$INPUT_ACTION$'!\nНатискання '$SETTINGS_INPUT_CONFIRM$' очистить стару прив'язку"
  SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Попередження: прив'язка вводу не може складатися лише з клавіш-модифікаторів"
  SETTINGS_PAGE_ACCOUNT: "Обліковий запис"
  SETTING_TELEMETRY_CONSENT: "Надіслати необов'язкові телеметричні дані"
  SETTING_TELEMETRY_CONSENT_TOOLTIP: "#T Згода на телеметрію\n#!Дозволити надсилання необов'язкових телеметричних даних до Paradox Interactive."