l_english:
 SETTINGS_PAGE_GRAPHICS: "Графіка"
 SETTINGS_PAGE_GAME: "Гра"
 SETTINGS_PAGE_SYSTEM: "Система"
 SETTINGS_PAGE_CONTROLS: "Керування"
 SETTINGS_PAGE_EDITOR: "Редактор"
 SETTINGS_PAGE_INTERFACE: "Інтерфейс"
 SETTINGS_PAGE_AUDIO: "Аудіо"
 SETTINGS_CATEGORY_SCREEN: "Екран"
 SETTINGS_CATEGORY_QUALITY: "Якість"
 OPTION_EASY: "Легко"
 OPTION_NORMAL: "Нормально"
 OPTION_HARD: "Складно"
 OPTION_NEVER: "Нізащо"
 OPTION_MONTHLY: "Кожного місяця"
 OPTION_HALFYEAR: "Кожні півроку"
 OPTION_YEARLY: "Кожен рік"
 OPTION_FIVE_YEAR: "Кожні п'ять років"
 OPTION_NO_AUTOSAVE: "Не виконувати автозберігання"
 SETTINGS_CATEGORY_ACCOUNT: "Обліковий запис"
 SETTINGS_CATEGORY_SYSTEM: "Система"
 SETTINGS_CATEGORY_CONTROLS: "Керування"
 SETTINGS_CATEGORY_CAMERA: "Камера"
 SETTINGS_CATEGORY_AUDIO: "Аудіо"
 SETTINGS_CATEGORY_GUI: "Інтерфейс"
 SETTINGS_CATEGORY_INPUT_BINDINGS: "Прив'язка клавіш вводу"
 DISCARD: "Скасувати"
 APPLY: "Застосувати"
 SAVE_AND_CLOSE: "Гаразд"
 SETTINGS: "Налаштування"
 REQUIRES_RESTART: "Потребує перезапуску"
 REQUIRE_RESTART_DESCRIPTION: "Деякі налаштування почнуть діяти тільки після перезапуску гри."
 DISABLED_BECAUSE_IS_SET: "Недоступно, тому що '$SETTING_NAME$' задане значення '$SETTING_VALUE$'"
 SETTINGS_INPUT_REMAP_INPUT: "Змінити прив'язку"
 SETTINGS_INPUT_CONFIRM: "Підтвердити"
 SETTINGS_INPUT_CANCEL: "Скасувати"
 SETTINGS_INPUT_CLEAR: "Очистити"
 SETTINGS_INPUT_SAVE_INPUT_PROFILE: "Зберегти профіль"
 SETTINGS_INPUT_LOAD_INPUT_PROFILE: "Завантажити профіль"
 SETTINGS_INPUT_RESET_INPUT_PROFILE: "Повернутися до початкових значень"
 SETTINGS_INPUT_BINDING_TEXT: "Вкажіть клавішу для дії '$INPUT_ACTION$':\n\n$INPUT_NAME$"
 SETTINGS_INPUT_BINDING_WARNING_TEXT: "Увага: Ця клавіша вже прив'язана до дії '$INPUT_ACTION$'!\nНатиснувши '$SETTINGS_INPUT_CONFIRM$' ви скасуєте існуючу прив'язку"
 SETTINGS_INPUT_BINDING_MODIFIERS_WARNING_TEXT: "Увага: прив'язка не може складатися лише з клавіш-модифікаторів"
 SETTINGS_PAGE_ACCOUNT: "Обліковий запис"
 SETTING_TELEMETRY_CONSENT: "Надіслати додаткову телеметрію"
 SETTING_TELEMETRY_CONSENT_TOOLTIP:0 "#T Згода на телеметрію\n#!Дозволити надсилати додаткову телеметричні дані до Paradox Interactive."