l_russian:
  SETTING_VALUE_NONE: "$VALUE$"
  SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
  SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
  SETTING_VALUE_SECONDS: "$VALUE$ сек."
  SETTING_VALUE_MINUTES: "$VALUE$ хв."
  SETTING_RENDERER: "Рендеринг"
  SETTING_RENDERER_TOOLTIP: "Визначає використовуваний рендерер."
  SETTING_VSYNC: "Вертикальна синхронізація"
  SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$\n#!Синхронізує частоту кадрів гри та монітора, зменшуючи розриви зображення на екрані.\n\nВимкнення цього параметра може підвищити продуктивність."
  SETTING_PORTRAIT_MULTI_SAMPLING: "Згладжування портретів"
  SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$\n#!Використання згладжування за технологією Alpha-To-Coverage для більш плавного накладання волосся.\n\nЗниження параметра може підвищити продуктивність."
  SETTING_MULTI_SAMPLING: "Згладжування (MSAA)"
  SETTING_MULTI_SAMPLING_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$\n#!При використанні згладжування з множинною вибіркою (MSAA) краї зображення стають більш гладкими.\n\nЗниження параметра може підвищити продуктивність."
  SETTING_ANTI_ALIASING: "Згладжування"
  SETTING_ANTI_ALIASING_TOOLTIP: "#T $SETTING_ANTI_ALIASING$\n#!При використанні згладжування краї зображення будуть менш різкими.\n\nРекомендуємо використовувати FXAA."
  OPTION_ANTI_ALIASING_DISABLED: "Вимк."
  OPTION_ANTI_ALIASING_FXAA: "FXAA"
  SETTING_UPSCALE: "Метод масштабування"
  SETTING_UPSCALE_TOOLTIP: "#T $SETTING_UPSCALE$#!\nМетоди масштабування дозволяють досягти вищої роздільної здатності за допомогою алгоритмічної підвищувальної дискретизації. Це може підвищити продуктивність, але існує ризик виникнення артефактів та іншої несподіваної поведінки.\n\nДоступність методів масштабування може залежати від вашої графічної карти."
  OPTION_UPSCALE_FSR2: "AMD FidelityFX Super Resolution 2"
  OPTION_UPSCALE_DLSS: "NVIDIA DLSS"
  OPTION_UPSCALE_XESS: "Intel® XeSS"
  SETTING_UPSCALE_QUALITY: "Якість масштабування"
  SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_UPSCALE_QUALITY$#!\nЗадає пріоритет методу масштабування від високої якості до високої продуктивності."
  OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "Висока якість"
  OPTION_UPSCALE_QUALITY_QUALITY: "Якість"
  OPTION_UPSCALE_QUALITY_BALANCED: "Збалансовано"
  OPTION_UPSCALE_QUALITY_PERFORMANCE: "Продуктивність"
  OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "Висока продуктивність"
  SETTING_ANISOTROPIC_FILTERING: "Фільтрація текстур"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Використання анізотропної фільтрації покращує зовнішній вигляд текстурованих поверхонь.\n\nЗниження параметра може підвищити продуктивність."
  SETTING_RESOLUTION: "Роздільна здатність"
  SETTING_RESOLUTION_TOOLTIP: "#T $SETTING_RESOLUTION$\n#!Якість зображення в грі.\n\nЗниження роздільної здатності може підвищити продуктивність.\n\n#X Роздільні здатності з непідтримуваним співвідношенням сторін можуть призвести до виходу елементів інтерфейсу за межі екрана#!"
  SETTING_WINDOWED_RESOLUTION: "Роздільна здатність у віконному режимі"
  SETTING_WINDOWED_RESOLUTION_TOOLTIP: "#T $SETTING_WINDOWED_RESOLUTION$\n#!Якщо гра запущена у віконному режимі — визначає роздільну здатність вікна.\n\nНеобхідно використовувати формат #b ЧИСЛО#!x#b ЧИСЛО#!.\n\n#X Роздільна здатність з непідтримуваним співвідношенням сторін може призвести до того, що інтерфейс виявиться за межами екрана#!"
  SETTING_RENDER_SCALE: "Розмір рендера"
  SETTING_RENDER_SCALE_TOOLTIP: "#T $SETTING_RENDER_SCALE$#!\nРозмір роздільної здатності рендера в грі відносно роздільної здатності екрана за вирахуванням інтерфейсу.\n\nЗниження параметра може підвищити продуктивність, але знизить якість зображення, тоді як збільшення понад 100% може підвищити якість, але, ймовірно, знизить продуктивність."
  SETTING_RENDER_SCALE_FORMAT: "$VALUE|%0$"
  SETTING_DISPLAY: "Монітор"
  SETTING_DISPLAY_TOOLTIP: "#T $SETTING_DISPLAY$\n#!Якщо у вашого комп'ютера кілька моніторів, виберіть той, який буде використовуватися в грі."
  SETTING_GRAPHICS_DEVICE: "Відеокарта"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$\n#!Виберіть, яка відеокарта буде використовуватися в грі.\n\nВикористання інтегрованої відеокарти або програмного рендерингу може знизити продуктивність."
  SETTING_SHADOW_MAP_RESOLUTION: "Якість тіней"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Якщо тіні увімкнені, параметр визначає роздільну здатність, з якою накладаються карти тіней.\n\nЗниження параметра може підвищити продуктивність."
  SETTING_DISPLAY_MODE: "Режим відображення"
  SETTING_DISPLAY_MODE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$\n#!Визначає, як буде відображатися гра на вашому екрані"
  SETTING_BLOOM_QUALITY: "Світіння"
  SETTING_MESH_LOD_BIAS: "Якість деталізації сітки"
  SETTING_MESH_LOD_FADE: "Згасання деталізації сітки"
  SETTING_TERRAIN_SMOOTHING: "Згладжування ландшафту"
  OPTION_FULLSCREEN: "Повноекранний"
  OPTION_FULLSCREEN_TOOLTIP: "#T $OPTION_FULLSCREEN$\n#!Відображати гру на весь екран. Налаштування розширення впливатимуть на чіткість зображення."
  OPTION_WINDOWED: "Віконний режим"
  OPTION_WINDOWED_TOOLTIP: "#T $OPTION_WINDOWED$\n#!Відображати гру у вікні. Налаштування роздільної здатності змінюють розмір вікна."
  OPTION_DISABLED: "Вимк."
  OPTION_OFF: "Вимк."
  OPTION_LOW: "Низький"
  OPTION_MEDIUM: "Середній"
  OPTION_HIGH: "Високий"
  OPTION_ULTRA: "Дуже високий"
  OPTION_CUSTOM: "Користувацький"
  OPTION_DEFAULT: "За замовчуванням"
  SETTINGS_CATEGORY_UI: "Інтерфейс"
  SETTINGS_CATEGORY_GAME: "Гра"
  SETTING_TEXTURE_QUALITY: "Якість текстур"
  SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_TEXTURE_QUALITY$#!\nРоздільна здатність завантажених текстур.\n\nЗниження параметра може підвищити продуктивність."
  SETTING_QUALITY: "Збережена настройка якості"
  SETTING_SFX: "Звукові ефекти"
  SETTING_UI: "Інтерфейс"
  SETTING_QUALITY_TOOLTIP: "#T $SETTING_QUALITY$\n#!Оберіть збережений параметр у додаткових налаштуваннях графіки внизу.\n\nНизьке значення збереженого параметра підвищить продуктивність."
  SETTING_BLOOM_QUALITY_TOOLTIP: "#T $SETTING_BLOOM_QUALITY$\n#!Вмикає ефект світіння, завдяки якому джерела особливо яскравого світла освітлюватимуть й інші частини зображення.\n\nЗниження значення може підвищити продуктивність."
  SETTING_DOF_TOOLTIP: "#T $SETTING_DOF$\n#!Вмикає глибину поля, що симулює об'єктив камери, розмиває частини зображення, які не перебувають у фокусі.\n\nВимкнення параметра може підвищити продуктивність."
  SETTING_LENS_FLARE_TOOLTIP: "#T $SETTING_LENS_FLARE$\n#!Вмикає ефект відблисків, що з'являється в яскраво освітлених місцях. Щоб ефект з'явився, необхідно ввімкнути світіння.\n\nВимкнення параметра може підвищити продуктивність."
  SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_SECONDARY_LENS_FLARE$\n#!Вмикає ефект вторинних відблисків, що з'являється в яскраво освітлених місцях. Щоб ефект з'явився, необхідно ввімкнути світіння.\n\nВимкнення параметра може підвищити продуктивність."
  SETTING_MAP_SSAO_TOOLTIP: "#T $SETTING_MAP_SSAO$\n#!Визначає, чи буде застосовуватися до карти перешкоджання навколишнього світла в екранному просторі.\n\nВимкнення параметра може підвищити продуктивність."
  SETTING_REFRACTION_TOOLTIP: "Відображати (чи ні) відбиття на воді."
  SETTING_REFRACTION_QUALITY_TOOLTIP: "#T $SETTING_REFRACTION_QUALITY$#!\nЯкість відбиття на воді (якщо вони відображаються).\n\nЗниження параметра може підвищити продуктивність."
  SETTING_MAPOBJECT_QUALITY_TOOLTIP: "#T $SETTING_MAPOBJECT_QUALITY$#!\nМаксимальний рівень якості відображення об'єктів на карті (будівлі тощо).\n\nЗниження параметра може підвищити продуктивність."
  SETTING_MESH_LOD_BIAS_TOOLTIP: "#T $SETTING_MESH_LOD_BIAS$#!\nЯкість деталізації об'єктів на карті (підрозділи тощо).\n\nЗниження параметра може підвищити продуктивність."
  SETTING_MESH_LOD_FADE_TOOLTIP: "#T $SETTING_MESH_LOD_FADE$\n#!Якщо ввімкнено цей параметр, у тривимірних моделях відбувається плавний перехід між різними рівнями деталізації при зміні масштабу.\n\nВимкнення параметра може підвищити продуктивність."
  SETTING_PROVINCE_NAMES_TOOLTIP: "Спосіб показувати на карті назви міст і провінцій."
  SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "Вмикати (чи ні) до кордонів країни на карті непрохідні ділянки."
  SETTING_LANGUAGE_TOOLTIP: "#T $SETTING_LANGUAGE$#!\nМова користувацького інтерфейсу."
  SETTING_ACCOUNT_EMAIL_TOOLTIP: "Адреса вашої ел. пошти для облікового запису Paradox"
  SETTING_FRAMERATE_CAP: "Обмеження кількості кадрів"
  SETTING_FRAMERATE_CAP_TOOLTIP: "#T $SETTING_FRAMERATE_CAP$#!\nОбмеження кількості кадрів на секунду, яку відображатиме гра.\n\nЗниження параметра може скоротити споживання електроенергії."
  OPTION_CAP_30: "30"
  OPTION_CAP_60: "60"
  OPTION_CAP_90: "90"
  OPTION_CAP_120: "120"
  OPTION_CAP_144: "144"
  OPTION_CAP_165: "165"
  SETTING_TEXTURE_STREAMING: "Стримінг текстур"
  SETTING_TEXTURE_STREAMING_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!\nТекстури підвантажуються за потреби.\n\nЗнижує навантаження на графічний процесор, але збільшує споживання ресурсів ЦПУ. Може підвищити продуктивність графічних карт з невеликим запасом пам'яті."
  SETTING_TEXTURE_STREAMING_CACHE: "Розмір кешу стримінгу текстур"
  SETTING_VALUE_MB: "$VALUE$ МБ"
  SETTING_ANIMATION_SPEED: "Швидкість анімації"
  SETTING_GUI_SCALING: "Масштабування інтерфейсу"
  SETTING_GUI_SCALING_TOOLTIP: "#T $SETTING_GUI_SCALING$\n#!Задає масштаб користувацького інтерфейсу. Зручно для великих роздільних здатностей екрана.\n\n#X Занадто високе значення параметра призведе до того, що елементи інтерфейсу не будуть поміщатися на екрані.#!"
  SETTING_TOOLS_GUI_SCALING: "Масштабування інтерфейсу інструментів"
  SETTING_TOOLS_GUI_SCALING_TOOLTIP: "#T $SETTING_TOOLS_GUI_SCALING$\n#!Задає масштаб користувацького інтерфейсу інструментів. Зручно для великих роздільних здатностей екрана.\n\n#X Занадто високе значення параметра призведе до того, що елементи інтерфейсу не будуть поміщатися на екрані!#!"
  SETTING_SCREEN_EDGE_SCROLL_MODE: "Переміщення мишею"
  SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "Вільне"
  SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "8 напрямків"
  SETTING_SCREEN_EDGE_SCROLL_DISABLED: "Вимк."
  SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#T $SETTING_SCREEN_EDGE_SCROLL_MODE$#!\nПоведінка камери при переміщенні мишею."
  SETTING_SCROLL_SPEED: "Швидкість перетягування"
  SETTING_SCROLL_SPEED_TOOLTIP: "#T $SETTING_SCROLL_SPEED$#!\nВизначає швидкість переміщення карти за допомогою клавіатури або миші."
  SETTING_CAMERA_ROTATION_SPEED: "Швидкість обертання камери"
  SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#T $SETTING_CAMERA_ROTATION_SPEED$#!\nШвидкість обертання камери."
  SETTING_ZOOM_SPEED: "Швидкість наближення"
  SETTING_ZOOM_SPEED_TOOLTIP: "#T $SETTING_ZOOM_SPEED$#!\nШвидкість наближення камери."
  SETTING_MOUSE_CURSOR_ZOOM_MODE: "Поведінка наближення"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "Відносно курсора"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: "Наближення до курсора"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Ігнорувати курсор"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_MOUSE_CURSOR_ZOOM_MODE$#!\nПоведінка камери при наближенні та віддаленні відносно курсора."
  SETTING_INPUT_DEVICE: "Пристрій введення"
  SETTING_EDITOR: "Редактор"
  SETTING_EDITOR_POSTFIX: "Постфікс для команди редактора"
  SETTING_EDITOR_OPEN_FILE_FORMAT: "Команда відкриття редактора"
  SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "Переглянути журнал команд"
  SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: "Команда відкриття редактора коду"
  SETTING_GRACEFUL_EXIT: "Вихід при помилці"
  SETTING_LANGUAGE: "Мова"
  MOUSE_AND_KEYBOARD: "Клавіатура та миша"
  GAMEPAD: "Геймпад"
  SETTING_MULTISAMPLING_DISABLED: "Вимкнено"
  SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Вимкнено"
  SETTING_ANISOTROPIC_FILTERING_DISABLED: "Вимкнено"
  SETTING_CAMERA_TILT: "Нахил камери"
  SETTING_CAMERA_STRATEGY: "Тип камери"
  SETTING_CENTERED_ZOOM_IN: "Наближення з центруванням"
  SETTING_CAMERA_SPEED: "Швидкість камери"
  CAMERA_TABLETOP: "Настільний вигляд"
  CAMERA_FPS: "Від першої особи"
  CAMERA_WASD: "Стиль WASD"
  SETTING_Music: "Музика"
  SETTING_Ambient: "Звуковий супровід"
  SETTING_Effects: "Ефекти"
  SETTING_Master: "Загальний рівень"
  SETTING_VO: "Закадровий голос"
  SETTING_VO_TOOLTIP: "#T Гучність закадрового голосу\n#!Задає гучність закадрового голосу в грі."
  SETTING_Master_TOOLTIP: "#T Основна гучність\n#!Задає гучність усіх звуків у грі."
  SETTING_Music_TOOLTIP: "#T Гучність музики\n#!Задає гучність музики."
  SETTING_Ambient_TOOLTIP: "#T Звуковий супровід\n#!Задає гучність звукового супроводу."
  SETTING_SFX_TOOLTIP: "#T Звукові ефекти\n#!Задає рівень гучності звукових ефектів (бою тощо)."
  SETTING_UI_TOOLTIP: "#T Інтерфейс\n#!Задає рівень гучності звуків інтерфейсу."
  SETTING_AUDIO_DEBUG_LOG_LEVEL: "Налагодження рівнів логування"
  SETTING_AUDIO_DEVICE_PROFILE: "Аудіопрофіль"
  SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "#T $SETTING_AUDIO_DEVICE_PROFILE$\n#!Виберіть аудіопрофіль під свої пристрої."
  SETTING_AUDIO_OPTION_SPEAKERS: "Колонки"
  SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "#T $SETTING_AUDIO_OPTION_SPEAKERS$\n#!Стандартне поєднання для колонок."
  SETTING_AUDIO_OPTION_HEADPHONES: "Навушники"
  SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "#T $SETTING_AUDIO_OPTION_HEADPHONES$\n#!Поєднання, що підходить для навушників."
  SETTING_AUDIO_OPTION_TV: "ТБ"
  SETTING_AUDIO_OPTION_TV_TOOLTIP: "#T $SETTING_AUDIO_OPTION_TV$\n#!Поєднання для колонок, вбудованих у телевізор або монітор."
  SETTING_AUDIO_OPTION_NIGHTMODE: "Нічний режим"
  SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "#T $SETTING_AUDIO_OPTION_NIGHTMODE$\n#!Приглушує звук для гри вночі, принижуючи високі частоти та знижуючи дальність динаміків."
  SETTING_MUSIC_DENSITY: "Інтенсивність музики"
  SETTING_MUSIC_DENSITY_TOOLTIP: "Визначає баланс між повноцінними композиціями, тишею та музичним фоном. \n\nНасичена = В основному йде послідовне відтворення музичних композицій, аналогічно радіостанції. \nЗбалансована = Ідеальний баланс між повноцінними композиціями, тишею та створенням музичного фону. \nЛегка = В основному фонова музика для передачі настрою гри без відчуття повтору після кількох годин."
  SETTING_AUTOSAVE: "Інтервал автозбережень"
  SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_AUTOSAVE$\n#!Задає частоту автозбереження гри."
  SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Записувати автозбереження в хмару (чи ні)."
  SETTING_CAMERA_FACE_NORTH_TOOLTIP: "Завжди розвертати ігрову камеру на північ чи ні."
  NO_AUTOSAVE: "Без автозбережень"
  SETTINGS_FILE_TRANSFER_SPEED: "Швидкість передачі файлів"
  SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "#T $File Transfer Speed$\n#!Задає максимальну швидкість передачі файлів збереженої гри в лобі мережевої гри.\n\nЗниження цього параметра може покращити стабільність мережі при підключенні до мережевих ігор, але це негативно позначиться на часі завантаження файлів."
  SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "Автозбереження в редакторі карт (хв.)"
  SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "Частота автозбережень в редакторі карт (хв.)"
  SETTING_NODE_EDITOR_DRAG_PAN_MODE: "Переміщення вузлів"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE: "Console auto-complete mode"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Full expand, iterate with tab"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "Partial expand until different"
  SETTINGS_CATEGORY_ACCESSIBILITY: "Спеціальні можливості"
  SETTING_COLOR_BLIND_MODE: "Режим розрізнюваних кольорів"
  SETTING_COLOR_BLIND_MODE_TOOLTIP: "#T $SETTING_COLOR_BLIND_MODE$\n#!Замінює кольори в грі на більш розрізнювані для людей, що страждають на дальтонізм."