l_english:
  SETTING_VALUE_NONE: "$VALUE$"
  SETTING_VALUE_TOTAL_PERCENTAGE: "$VALUE|%/0$"
  SETTING_VALUE_PERCENTAGE: "$VALUE|%0$"
  SETTING_VALUE_SECONDS: "$VALUE$ секунд"
  SETTING_VALUE_MINUTES: "$VALUE$ хвилин"
  SETTING_RENDERER: "Візуалізатор"
  SETTING_RENDERER_TOOLTIP: "Визначає, який візуалізатор використовується."
  SETTING_VSYNC: "VSync"
  SETTING_VSYNC_TOOLTIP: "#T $SETTING_VSYNC$"
  SETTING_PORTRAIT_MULTI_SAMPLING: "#!Надає грі та вашому монітору однакову частоту кадрів, зменшуючи розриви екрана."
  SETTING_PORTRAIT_MULTI_SAMPLING_TOOLTIP: ""
  SETTING_MULTI_SAMPLING: "Вимкнення може покращити продуктивність."
  SETTING_MULTI_SAMPLING_TOOLTIP: "Мультисемплінг портретів"
  SETTING_ANTI_ALIASING: "#T $SETTING_PORTRAIT_MULTI_SAMPLING$"
  SETTING_ANTI_ALIASING_TOOLTIP: "#!Використання мультисемплінгу для Alpha-To-Coverage робить змішування волосся більш плавним."
  OPTION_ANTI_ALIASING_DISABLED: ""
  OPTION_ANTI_ALIASING_FXAA: "Нижчі налаштування збільшують продуктивність."
  SETTING_UPSCALE: "Згладжування (MSAA)"
  SETTING_UPSCALE_TOOLTIP: "#T $SETTING_MULTI_SAMPLING$"
  OPTION_UPSCALE_FSR2: "#!Використання багатовибіркового згладжування (MSAA) зробить краї зображень більш гладкими."
  OPTION_UPSCALE_DLSS: ""
  OPTION_UPSCALE_XESS: "Нижчі налаштування можуть збільшити продуктивність."
  SETTING_UPSCALE_QUALITY: "Згладжування"
  SETTING_UPSCALE_QUALITY_TOOLTIP: "#T $SETTING_ANTI_ALIASING$"
  OPTION_UPSCALE_QUALITY_ULTRA_QUALITY: "#!Використання згладжування зробить краї зображень більш гладкими."
  OPTION_UPSCALE_QUALITY_QUALITY: ""
  OPTION_UPSCALE_QUALITY_BALANCED: "Рекомендується FXAA."
  OPTION_UPSCALE_QUALITY_PERFORMANCE: "Вимкнено"
  OPTION_UPSCALE_QUALITY_ULTRA_PERFORMANCE: "FXAA"
  SETTING_ANISOTROPIC_FILTERING: "Метод масштабування"
  SETTING_ANISOTROPIC_FILTERING_TOOLTIP: "#T $SETTING_UPSCALE$#!"
  SETTING_RESOLUTION: "Методи масштабування можуть бути використані для досягнення вищої роздільної здатності екрана за допомогою алгоритмічного збільшення вибірки. Це може покращити продуктивність, але може призвести до візуальних артефактів або іншої неочікуваної поведінки."
  SETTING_RESOLUTION_TOOLTIP: ""
  SETTING_RENDER_SCALE: "Доступні методи масштабування можуть залежати від вашої відеокарти."
  SETTING_RENDER_SCALE_TOOLTIP: "AMD FidelityFX Super Resolution 2"
  SETTING_RENDER_SCALE_FORMAT: "NVIDIA DLSS"
  SETTING_DISPLAY: "Intel® XeSS"
  SETTING_DISPLAY_TOOLTIP: "Якість масштабування"
  SETTING_GRAPHICS_DEVICE: "#T $SETTING_UPSCALE_QUALITY$#!"
  SETTING_GRAPHICS_DEVICE_TOOLTIP: "Встановлює фокус методу масштабування від найвищої якості до найвищої продуктивності."
  SETTING_SHADOW_MAP_RESOLUTION: "Надультра Якість"
  SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP: "Якість"
  SETTING_DISPLAY_MODE: "Збалансовано"
  SETTING_DISPLAY_MODE_TOOLTIP: "Продуктивність"
  SETTING_BLOOM_QUALITY: "Надультра Продуктивність"
  SETTING_MESH_LOD_BIAS: "Фільтрація текстур"
  SETTING_MESH_LOD_FADE: "#T $SETTING_ANISOTROPIC_FILTERING$"
  SETTING_TERRAIN_SMOOTHING: "#!Використання анізотропної фільтрації покращить вигляд текстурованих поверхонь."
  OPTION_FULLSCREEN: ""
  OPTION_FULLSCREEN_TOOLTIP: "Нижчі налаштування можуть збільшити продуктивність."
  OPTION_WINDOWED: "Роздільна здатність"
  OPTION_WINDOWED_TOOLTIP: "#T $SETTING_RESOLUTION$"
  OPTION_DISABLED: "#!Встановлює якість зображення гри."
  OPTION_OFF: "Нижчі роздільні здатності можуть підвищити продуктивність."
  OPTION_LOW: "#X Роздільна здатність гри з непідтримуваним співвідношенням сторін може призвести до того, що інтерфейси з'являться за межами екрана#!"
  OPTION_MEDIUM: "Масштаб рендерингу"
  OPTION_HIGH: "#T $SETTING_RENDER_SCALE$#!"
  OPTION_VERY_HIGH: "Масштаб роздільної здатності рендерингу гри відносно основної роздільної здатності, за винятком користувацького інтерфейсу."
  OPTION_ULTRA: "Нижчі налаштування можуть підвищити продуктивність, але зменшать загальну точність відтворення, тоді як значення вище 100% можуть підвищити точність відтворення, але, ймовірно, погіршать продуктивність."
  OPTION_CUSTOM: "$VALUE|%0$"
  OPTION_DEFAULT: "Монітор"
  SETTINGS_CATEGORY_UI: "#T $SETTING_DISPLAY$"
  SETTINGS_CATEGORY_GAME: "#!Якщо ваш комп'ютер має кілька моніторів, оберіть той, який буде використовувати гра."
  SETTING_TEXTURE_QUALITY: "Відеокарта"
  SETTING_TEXTURE_QUALITY_TOOLTIP: "#T $SETTING_GRAPHICS_DEVICE$"
  SETTING_QUALITY: "#!Вибирає, яку відеокарту використовуватиме гра."
  SETTING_SFX: "Використання інтегрованої відеокарти або програмного рендерера може знизити продуктивність."
  SETTING_UI: "Якість тіней"
  SETTING_QUALITY_TOOLTIP: "#T $SETTING_SHADOW_MAP_RESOLUTION$"
  SETTING_BLOOM_QUALITY_TOOLTIP: "#!Визначає роздільну здатність, з якою рендеряться тіньові карти, якщо тіні увімкнено."
  SETTING_DOF_TOOLTIP: "Нижчі налаштування можуть підвищити продуктивність."
  SETTING_LENS_FLARE_TOOLTIP: "Режим відображення"
  SETTING_SECONDARY_LENS_FLARE_TOOLTIP: "#T $SETTING_DISPLAY_MODE$"
  SETTING_MAP_SSAO_TOOLTIP: "#!Визначає, як відображати гру на вашому екрані"
  SETTING_REFRACTION_TOOLTIP: "Сяйво"
  SETTING_REFRACTION_QUALITY_TOOLTIP: "Якість деталізації сітки"
  SETTING_MAPOBJECT_QUALITY_TOOLTIP: "Згасання деталізації сітки"
  SETTING_MESH_LOD_BIAS_TOOLTIP: "Згладжування ландшафту"
  SETTING_MESH_LOD_FADE_TOOLTIP: "На весь екран"
  SETTING_PROVINCE_NAMES_TOOLTIP: "#T $OPTION_FULLSCREEN$"
  SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP: "#!Відображає гру на весь екран. Налаштування роздільної здатності змінить чіткість зображення."
  SETTING_LANGUAGE_TOOLTIP: "У вікні"
  SETTING_ACCOUNT_EMAIL_TOOLTIP: "#T $OPTION_WINDOWED$"
  SETTING_FRAMERATE_CAP: "#!Відображає гру у вікні. Налаштування роздільної здатності змінює розмір вікна."
  SETTING_FRAMERATE_CAP_TOOLTIP: "Вимкнено"
  OPTION_CAP_30: "Вимкнено"
  OPTION_CAP_60: "Низьке"
  OPTION_CAP_90: "Середнє"
  OPTION_CAP_120: "Високе"
  OPTION_CAP_144: "Дуже високе"
  OPTION_CAP_165: "Ультра"
  SETTING_TEXTURE_STREAMING: "Власне"
  SETTING_TEXTURE_STREAMING_TOOLTIP: "За замовчуванням"
  SETTING_TEXTURE_STREAMING_CACHE: "Інтерфейс"
  SETTING_VALUE_MB: "Гра"
  SETTING_ANIMATION_SPEED: "Якість текстур"
  SETTING_GUI_SCALING: "#T $SETTING_TEXTURE_QUALITY$#!"
  SETTING_GUI_SCALING_TOOLTIP: "Керує роздільною здатністю завантажуваних текстур."
  SETTING_TOOLS_GUI_SCALING: ""
  SETTING_TOOLS_GUI_SCALING_TOOLTIP: "Нижчі налаштування можуть підвищити продуктивність."
  SETTING_SCREEN_EDGE_SCROLL_MODE: "Предустановки якості"
  SETTING_SCREEN_EDGE_SCROLL_MODE_FREE: "SFX"
  SETTING_SCREEN_EDGE_SCROLL_MODE_8_DIRECTIONS: "Інтерфейс"
  SETTING_SCREEN_EDGE_SCROLL_DISABLED: "#T $SETTING_QUALITY$"
  SETTING_SCREEN_EDGE_SCROLL_MODE_TOOLTIP: "#!Оберіть предустановку розширених графічних налаштувань нижче."
  SETTING_SCROLL_SPEED: ""
  SETTING_SCROLL_SPEED_TOOLTIP: "Низька предустановка підвищить продуктивність."
  SETTING_CAMERA_ROTATION_SPEED: "#T $SETTING_BLOOM_QUALITY$"
  SETTING_CAMERA_ROTATION_SPEED_TOOLTIP: "#!Увімкнути ефект \"bloom\", де надзвичайно яскраві світла розсіюються на інші частини зображення."
  SETTING_ZOOM_SPEED: ""
  SETTING_ZOOM_SPEED_TOOLTIP: "Нижчі налаштування можуть підвищити продуктивність."
  SETTING_MOUSE_CURSOR_ZOOM_MODE: "#T $SETTING_DOF$"
  SETTING_MOUSE_CURSOR_ZOOM_MODE_RELATIVE_CURSOR: "#!Увімкнути глибину різкості для імітації об'єктива камери, розмиває нефокусні точки зображення."
  SETTING_MOUSE_CURSOR_ZOOM_MODE_ZOOM_IN_TO_CURSOR: ""
  SETTING_MOUSE_CURSOR_ZOOM_MODE_IGNORE_CURSOR: "Вимкнення може підвищити продуктивність."
  SETTING_MOUSE_CURSOR_ZOOM_MODE_TOOLTIP: "#T $SETTING_LENS_FLARE$"
  SETTING_INPUT_DEVICE: "#!Увімкнути ефект відблиску лінзи, який з'являється в сильно освітлених областях. Ефект \"bloom\" має бути увімкнений для появи цього ефекту."
  SETTING_EDITOR: ""
  SETTING_EDITOR_POSTFIX: "Вимкнення може підвищити продуктивність."
  SETTING_EDITOR_OPEN_FILE_FORMAT: "#T $SETTING_SECONDARY_LENS_FLARE$"
  SETTING_LOG_VIEWER_OPEN_FILE_FORMAT: "#!Увімкнути вторинний ефект відблиску лінзи, який з'являється в сильно освітлених областях. Ефект \"bloom\" має бути увімкнений для появи цього ефекту."
  SETTING_CODE_EDITOR_OPEN_FILE_FORMAT: ""
  SETTING_GRACEFUL_EXIT: "Вимкнення може підвищити продуктивність."
  SETTING_LANGUAGE: "#T $SETTING_MAP_SSAO$"
  MOUSE_AND_KEYBOARD: "#!Визначає, чи слід застосовувати екранне затемнення навколишнього середовища до мапи."
  GAMEPAD: ""
  SETTING_MULTISAMPLING_DISABLED: "Вимкнення може підвищити продуктивність."
  SETTING_PORTRAIT_MULTISAMPLING_DISABLED: "Визначає, чи з'являються заломлення на воді."
  SETTING_ANISOTROPIC_FILTERING_DISABLED: "#T $SETTING_REFRACTION_QUALITY$#!"
  SETTING_CAMERA_TILT: "Контролює якість заломлень води, якщо вони увімкнені."
  SETTING_CAMERA_STRATEGY: ""
  SETTING_CENTERED_ZOOM_IN: "Нижчі налаштування можуть підвищити продуктивність."
  SETTING_CAMERA_SPEED: "#T $SETTING_MAPOBJECT_QUALITY$#!"
  CAMERA_TABLETOP: "Визначає найвищий рівень якості об'єктів мапи (таких як будівлі)."
  CAMERA_FPS: ""
  CAMERA_WASD: "Нижчі налаштування можуть підвищити продуктивність."
  SETTING_Music: "#T $SETTING_MESH_LOD_BIAS$#!"
  SETTING_Ambient: "Визначає якість LOD (рівнів деталізації) для об'єктів мапи, таких як моделі юнітів."
  SETTING_Effects: ""
  SETTING_Master: "Нижчі налаштування можуть підвищити продуктивність."
  SETTING_VO: "#T $SETTING_MESH_LOD_FADE$"
  SETTING_VO_TOOLTIP: "#!Якщо увімкнено, 3D-моделі плавно переходять між різними рівнями деталізації (LOD) при збільшенні або зменшенні масштабу."
  SETTING_Master_TOOLTIP: ""
  SETTING_Music_TOOLTIP: "Вимкнення може підвищити продуктивність."
  SETTING_Ambient_TOOLTIP: "Визначає, як назви міст і провінцій відображаються на мапі."
  SETTING_SFX_TOOLTIP: "Визначає, чи включено непрохідну місцевість до кордонів нації на карті."
  SETTING_UI_TOOLTIP: "#T $SETTING_LANGUAGE$#!"
  SETTING_AUDIO_DEBUG_LOG_LEVEL: "Визначає мову інтерфейсу користувача."
  SETTING_AUDIO_DEVICE_PROFILE: "Ваша електронна пошта облікового запису Paradox"
  SETTING_AUDIO_DEVICE_PROFILE_TOOLTIP: "Максимальна кількість кадрів на секунду"
  SETTING_AUDIO_OPTION_SPEAKERS: "#T $SETTING_FRAMERATE_CAP$#!"
  SETTING_AUDIO_OPTION_SPEAKERS_TOOLTIP: "Максимальна кількість кадрів на секунду (FPS), яку гра відображатиме."
  SETTING_AUDIO_OPTION_HEADPHONES: ""
  SETTING_AUDIO_OPTION_HEADPHONES_TOOLTIP: "Нижчі налаштування можуть зменшити споживання енергії."
  SETTING_AUDIO_OPTION_TV: "30"
  SETTING_AUDIO_OPTION_TV_TOOLTIP: "60"
  SETTING_AUDIO_OPTION_NIGHTMODE: "90"
  SETTING_AUDIO_OPTION_NIGHTMODE_TOOLTIP: "120"
  SETTING_MUSIC_DENSITY: "144"
  SETTING_MUSIC_DENSITY_TOOLTIP: "165"
  SETTING_AUTOSAVE: "Потокове передавання текстур"
  SETTING_AUTOSAVE_TOOLTIP: "#T $SETTING_TEXTURE_STREAMING$#!"
  SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP: "Текстури завантажуються за потреби."
  SETTING_CAMERA_FACE_NORTH_TOOLTIP: ""
  NO_AUTOSAVE: "Знижує використання пам'яті графічного процесора за рахунок деяких накладних витрат часу центрального процесора. Може збільшити продуктивність для графічних процесорів з невеликим обсягом пам'яті."
  SETTING_ENABLE_PARTICLES: "Розмір кешу потокового передавання текстур"
  SETTING_ENABLE_PARTICLES_TOOLTIP: "$VALUE$ МБ"
  SETTINGS_FILE_TRANSFER_SPEED: "Швидкість анімації"
  SETTINGS_FILE_TRANSFER_SPEED_TOOLTIP: "Масштабування графічного інтерфейсу"
  SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES: "#T $SETTING_GUI_SCALING$"
  SETTING_MAP_EDITOR_AUTOSAVE_INTERVAL_MINUTES_TOOLTIP: "#!Встановлює масштаб всього користувацького інтерфейсу. Корисно для вищих роздільних здатностей екрана."
  SETTING_NODE_EDITOR_DRAG_PAN_MODE: ""
  SETTING_CONSOLE_AUTOCOMPLETE_MODE: "#X Встановлення занадто високого значення призведе до того, що інтерфейси не будуть належним чином вміщуватися на екрані!#!"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE_FULL_EXPAND: "Масштабування графічного інтерфейсу інструментів"
  SETTING_CONSOLE_AUTOCOMPLETE_MODE_PARTIAL_EXPAND: "#T $SETTING_TOOLS_GUI_SCALING$"
  SETTINGS_CATEGORY_ACCESSIBILITY: "#!Встановлює масштаб інтерфейсу користувача інструментів. Корисно для вищих роздільних здатностей екрана."
  SETTING_COLOR_BLIND_MODE: ""
  SETTING_COLOR_BLIND_MODE_TOOLTIP: "#X Встановлення занадто високого значення призведе до того, що інтерфейси не будуть належним чином вміщуватися на екрані!#!"